from enum import StrEnum


class ApprovalStage(StrEnum):
    CLIENT_PROFILE_REVIEW = "CLIENT_PROFILE_REVIEW"
    TASK_EXECUTION = "TASK_EXECUTION"
    RESULT_EXPORT = "RESULT_EXPORT"


class ExecutionState(StrEnum):
    CREATED = "CREATED"
    WAIT_LOGIN = "WAIT_LOGIN"
    READY = "READY"
    WAIT_HUMAN_APPROVAL = "WAIT_HUMAN_APPROVAL"
    OPEN_PLATFORM = "OPEN_PLATFORM"
    SEND_QUERY = "SEND_QUERY"
    WAIT_RESPONSE = "WAIT_RESPONSE"
    VERIFY_COMPLETE = "VERIFY_COMPLETE"
    SAVE_RESULT = "SAVE_RESULT"
    DELETE_CHAT = "DELETE_CHAT"
    VERIFY_DELETE = "VERIFY_DELETE"
    NEXT_TASK = "NEXT_TASK"
    COMPLETED = "COMPLETED"
    PAUSED = "PAUSED"
    FAILED = "FAILED"


class PauseReason(StrEnum):
    CAPTCHA = "CAPTCHA"
    LOGIN_EXPIRED = "LOGIN_EXPIRED"
    SECURITY_CHALLENGE = "SECURITY_CHALLENGE"
    PAGE_ABNORMAL = "PAGE_ABNORMAL"
    RATE_LIMITED = "RATE_LIMITED"
    ACCOUNT_RESTRICTED = "ACCOUNT_RESTRICTED"
    COMPLETION_UNCERTAIN = "COMPLETION_UNCERTAIN"
    SESSION_LOST = "SESSION_LOST"
    OPERATOR_REQUESTED = "OPERATOR_REQUESTED"
